fix: popup window size
CryptKeeperZK/crypt-keeper-extension pull request #130
Opened 2023-02-28 21:20 UTC by 0xmad

## Explanation

Currently, there is an issue with scaling (extension styles lost proportions).
This PR is supposed to fix this issue by changing global popup styles.

Details are below:
- [x] Remove overflow: hidden for body
- [x] Change breakpoint for larger screens and use percent values

## More Information

Closes #106

## Screenshots/Screencaps

### Before

Scale x1.5
![image](https://user-images.githubusercontent.com/14254374/221981850-0ff7c736-f304-4cae-beaf-47ddce79fc6b.png)

### After

Scale x1
![image](https://user-images.githubusercontent.com/14254374/221981337-3ae244c0-2429-4841-bdaa-03faa62ae101.png)
![image](https://user-images.githubusercontent.com/14254374/221981616-0795ff83-99c0-4659-b20b-3a23ae5554c1.png)

Scale x1.5
![image](https://user-images.githubusercontent.com/14254374/221982191-b32762f5-5151-4ac5-bc22-a93404c8a960.png)
![image](https://user-images.githubusercontent.com/14254374/221982488-af829a08-1b0d-4539-92e0-df1cc87ea958.png)

## Manual Testing Steps

1. Install extension
2. Try to change Scale in display settings
3. Check popup proportions

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-03-01 10:51 UTC, iskdrews requested changes
It is unfortunately still buggy in my end. That's how it looks. 
![Screenshot_20230301_114802](https://user-images.githubusercontent.com/36774944/222118258-03be12c4-487b-4765-aa37-0753e3be442d.png)

Here are my display settings:
1. Global scope: 100%
2. Font DPI: 110
![Screenshot_20230301_115047](https://user-images.githubusercontent.com/36774944/222118704-93b68ce4-579d-43aa-bfa0-8ae5553fd6b3.png)

Could you please try changing your DPI settings and test it from your end?

2023-03-08 22:28 UTC, 0xmad commented
@iskdrews with same dpi it looks good from my side.
![image](https://user-images.githubusercontent.com/14254374/223865318-7a31b6c4-2010-4f7f-9604-83742fdf104c.png)

2023-03-09 16:58 UTC, 0xmad commented
@iskdrews yes, now it looks good (just improved breakpoints).

![image](https://user-images.githubusercontent.com/14254374/224099063-17085ef8-5fc3-45ab-a0f4-4603f0747139.png)
![image](https://user-images.githubusercontent.com/14254374/224099640-f24da1d0-6774-41d3-b3b3-3f19e838c397.png)

2023-03-10 20:27 UTC, iskdrews approved these changes
Thanks @0xmad

2023-03-10 20:27 UTC, merged