fix: clean pending requests
CryptKeeperZK/crypt-keeper-extension pull request #186
Opened 2023-03-17 15:46 UTC by iskdrews

## Explanation

chore:
- Making sure to clean any pendingRequested related to any opened window which is closed from the user via clicking on "x" button.

enhance:
   - Adding a button for creating a new identity in the demo website.

## More Information

Fixes #187 
Closes #14
Related to #140  
Related to #183 

## Screenshots/Screencaps

### Before

### After

## Manual Testing Steps

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

### + If there are functional changes:

- [ ] Manual testing complete & passed
- [ ] "Extension QA Board" label has been applied

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-03-17 20:38 UTC, 0xmad requested changes
@iskdrews thanks for the fix!
There are some comments related to encapsulation for BrowserUtils class.

2023-03-17 20:38 UTC, 0xmad commented on demo/index.tsx
> +  const createIdentity = useCallback(async () => {
I think you don't need async/await here and you can use onClick handler without arrow function.

2023-03-17 20:38 UTC, 0xmad commented on demo/index.tsx
> +        <button onClick={() => createIdentity()}>Create</button> <br />
```suggestion
        <button onClick={createIdentity}>Create</button> <br />
```

2023-03-17 20:38 UTC, 0xmad commented on src/types/index.ts
> +  windowId: number | undefined;
```suggestion
  windowId?: number;
```

2023-03-17 20:38 UTC, 0xmad commented on src/background/zkKeeper.ts
> +          BrowserUtils.cached = null;
I don't think it's a good idea to change cached value outside `BrowserUtils` class.
I'd move this logic inside the class.

2023-03-17 20:38 UTC, 0xmad commented on src/background/controllers/browserUtils.ts
>    public constructor() {
You can remove constructor if you don't need it

2023-03-17 20:38 UTC, 0xmad commented on src/background/controllers/requestManager.ts
> +  public finilizeRequestOnRemovedWindow = async (windowId: number | undefined): Promise<boolean> => {
```suggestion
  public finilizeRequestOnRemovedWindow = async (windowId?: number): Promise<boolean> => {
```

2023-03-17 20:38 UTC, 0xmad commented on src/background/controllers/requestManager.ts
> +    windowId: number | undefined,
```suggestion
    windowId?: number,
```

2023-03-19 09:13 UTC, iskdrews commented
Hi @0xmad thanks so much for your comments. 
I tried to move the code back to BrowserUtils class, but there is a cyclic dependency happened with `BrowserUtils` and `RequestManager` please review my workaround to resolve this. Thanks.

2023-03-20 19:42 UTC, 0xmad approved these changes
@iskdrews thanks! Feel free to merge when you are ready :)

2023-03-20 20:15 UTC, merged