Feature/enhance backup
CryptKeeperZK/crypt-keeper-extension pull request #305
Opened 2023-05-02 18:33 UTC by iskdrews

## Explanation

## More Information

## Screenshots/Screencaps

## Manual Testing Steps

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-05-02 20:00 UTC, AtHeartEngineer approved these changes

2023-05-02 20:17 UTC, 0xmad requested changes
@iskdrews thanks, there are just some refactoring suggestions and design improvements.

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/approval/index.ts
> +    if (authenticBackupCiphertext) await this.approvals.set(authenticBackupCiphertext);
Maybe we need throw error if backup is corrupted?

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/crypto/index.ts
> +  return true;
```suggestion
  return transitHmac === decryptedHmac;
```

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/crypto/index.ts
> +  return hmac + ciphertext;
```suggestion
  return `${hmac}${ciphertext}`;
```

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/zkIdentity/index.ts
> +    if (authenticBackupCiphertext) await this.identitiesStore.set<string>(authenticBackupCiphertext);
Same here with error case

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/lock/index.ts
> +    if (cipherText) {
It's better to get rid of nested conditions

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/lock/index.ts
> +            authenticBackupCiphertext: this.isBackupCiphertextAutentic(backupCiphertext),
You can move it to a variable and get rid of code duplication

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/lock/index.ts
> +    else {
No need in else case here you can just return the value

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/lock/index.ts
> +  private isBackupCiphertextAutentic = (backupCiphertext: string): string => {
Methods which starts with `is` is supposed to return boolean value. I'd rename it to `getBackupCiphertextAutentic`

2023-05-02 20:17 UTC, 0xmad commented on src/background/services/lock/index.ts
> +  private isHmacAuthentic = (ciphertext: string): { isHmacAuthentic: boolean; authenticCiphertext?: string } => {
Same here with method name, I'd rename it to `getHmacAuthenticData`

2023-05-03 14:41 UTC, 0xmad commented on src/background/services/lock/index.ts
>    };
```suggestion
  private isLockerPasswordAuthentic = async (password: string): Promise<boolean> => {
    if (!password) throw new Error("Password is not provided");

    const cipherText = await this.passwordStorage.get<string>();
    
    if (!cipherText) {
      return false;
    }
    
    const decryptedPasswordChecker = cryptoDecrypt(cipherText, password);
    return decryptedPasswordChecker === this.passwordChecker;
  };
```

2023-05-03 14:41 UTC, 0xmad commented on src/background/services/lock/index.ts
> +  };
```suggestion
  private isNewOnboarding = async () => {
    const cipherText = await this.passwordStorage.get<string>();
    
    return !cipherText;
  };
```

2023-05-03 14:41 UTC, 0xmad commented on src/background/services/lock/index.ts
> +    this.backupService = BackupService.getInstance();
I don't think it's correct to use backup service inside backupable. You can move `getAuthenticBackupCiphertext` method to crypto service and import here so with don't have cycle dependency between services.

2023-05-03 14:41 UTC, 0xmad commented on src/background/services/approval/index.ts
> +    this.backupService = BackupService.getInstance();
The same here for backup service and backupable

2023-05-03 14:41 UTC, 0xmad commented on src/background/services/zkIdentity/index.ts
> +    this.backupService = BackupService.getInstance();
And the last with backup service and backupable

2023-05-03 19:39 UTC, 0xmad approved these changes
@iskdrews thanks!

2023-05-03 19:44 UTC, merged