feat: mnemonic integration
CryptKeeperZK/crypt-keeper-extension pull request #361
Opened 2023-05-10 21:40 UTC by 0xmad

## Explanation

This PR adds integration for mnemonic generation.
This is a part of BIP39 integration.

Details are below:
- [x] Integrate mnemonic ui and services
- [x] Move mnemonic generation to ui page
- [x] Update e2e to support additional onboarding step
- [x] Support migration for users who does not have mnemonic

## More Information

Blocked by #355
Closes #356 

## Screenshots/Screencaps

N/A

## Manual Testing Steps

1. Reinstall extension
3. Complete password onboarding
4. Complete mnemonic onboarding
5. See home page is loaded

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-05-12 14:25 UTC, 0xisk requested changes
Thanks @0xmad, just some minor comments.

2023-05-12 14:25 UTC, 0xisk commented on src/background/services/wallet/index.ts
It's not clear for me why you moved the ExternalWallet service logic to the MiscStorage, I mean we could need to add other specific functions to ExternalWallet service.

2023-05-12 14:25 UTC, 0xisk commented on src/background/cryptKeeper.ts
> +    this.walletService = MiscStorageService.getInstance();
Could we also rename `this.walletService` to `this.miscStorageService`?

2023-05-12 14:25 UTC, 0xisk commented on src/constants/rpcActions.ts
> +  SAVE_MNEMONIC = "rpc/mnemonic/save",
Just a TODO for future, I think its good to have a convention in naming the rpc end points here. 
I would say sth like `rpc/SERVICE_NAME/SERVICE_FUNCTION`

2023-05-15 14:12 UTC, 0xmad commented on src/background/services/wallet/index.ts
Because it's only for storage purpose and we don't need any logic around it expect setting and getting.

2023-05-15 17:17 UTC, 0xisk commented on src/constants/rpcActions.ts
> +  SAVE_MNEMONIC = "rpc/mnemonic/save",
It's good for now, tbd later.

2023-05-15 17:17 UTC, 0xisk commented on src/background/services/wallet/index.ts
Good for now, maybe in future we would need to separate between them.

2023-05-15 17:20 UTC, 0xisk approved these changes
Thanks @0xmad, approved just I left one minor comment.

2023-05-15 17:20 UTC, 0xisk commented on src/background/cryptKeeper.ts
> +    this.keyStorageService = KeyStorageService.getInstance();
Maybe just move this line `this.keyStorageService = KeyStorageService.getInstance();` up before `this.backupService = BackupService.getInstance()` so we have in the end the backup listeners.

2023-05-15 19:12 UTC, merged