feat: use `@cryptkeeper/providers` for demo
CryptKeeperZK/crypt-keeper-extension pull request #557
Opened 2023-06-26 16:52 UTC by 0xmad

## Explanation

This PR adds example how to use `@cryptkeeper/providers` package.

## More Information

Related to #92
Blocked by #555 

## Screenshots/Screencaps

N/A

## Manual Testing Steps

N/A

## Pre-Merge Checklist

- [x] PR template is filled out
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-06-27 08:49 UTC, 0xisk requested changes

2023-06-27 08:49 UTC, 0xisk commented on packages/app/src/background/injectedScript.ts
Why removing `injectedScript`?

2023-06-27 12:34 UTC, 0xmad commented on packages/app/src/background/injectedScript.ts
Because injection is moved to client side. User needs to install provider package which initializes provider and sets cryptkeeper var.

2023-06-27 12:42 UTC, 0xisk commented on packages/app/src/background/injectedScript.ts
Let's just keep this PR only related to use `@cryptkeeper/providers` inside `demo`. And the other point needs to be discussed.

2023-06-29 08:30 UTC, 0xisk approved these changes
Thanks @0xmad :rocket: 
I'll make a follow up PR for adding more enhancements.

2023-06-29 08:30 UTC, merged