feat: backup rollback
CryptKeeperZK/crypt-keeper-extension pull request #670
Opened 2023-08-01 23:38 UTC by 0xmad

## Explanation

This PR supports rollback storage for unsuccessful backup uploads.

Details are below:
- [x] Add rollback for unsuccessful backup uploads
- [x] Add restore/download storage methods for backupables
- [x] Add e2e tests for invalid backup uploads

## More Information

Closes #330 

## Screenshots/Screencaps

N/A

## Manual Testing Steps

1. Try to upload any invalid backup file from `packages/e2e/backups`.
2. Check errors
3. Try to upload valid backup file or create account with password
4. Check lock/unlock functions

## Pre-Merge Checklist

- [x] PR template is filled out
- [x] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [x] PR is linked to the appropriate GitHub issue
- [x] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-08-03 10:00 UTC, 0xisk requested changes
Thanks @0xmad, here are my observations for doing user manual testing: 

**1.** Uploaded `2_invalid_backup.josn`  with having `123456Qq@` as a password for both fields, but got error saying `This ciphertext is not authentic`
![Screenshot_20230803_115119](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/ea3393e0-9171-4fa6-9684-12421d22b3ee)

**2.** Trying again with same with having the same upload window opened from step (1), and uploading the same backup file from step (1), and writing the same passwords from step (1). But I got different error this time, "Passwords don't match"
![Screenshot_20230803_115038](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/386623d5-14cc-40ea-b6d2-86ea9baff1bb)

**3.** Then still with having the same window opened, I tried the same INVALID_BACKUP files. But was always getting `Passwords don't match`
![Screenshot_20230803_115131](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/33b02a89-73c5-4fa6-ab97-4fbc367dbe5a)
![Screenshot_20230803_115137](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/6c74b831-f91a-40c9-ad93-2f10ce9fed75)
![Screenshot_20230803_115147](https://github.com/CryptKeeperZK/crypt-keeper-extension/assets/36774944/86655de3-70bb-43c4-b580-2248f530fed9)

**4.** I closed the same window opened for Steps (1, 2, 3) and clicked again on Upload backup from settings page to open a new window, then I tried with 0_backup file which is simply the valid file and as expected it worked without errors.

2023-08-03 10:10 UTC, 0xisk commented
@0xmad I noticed that you checked `IF this PR fixes a bug, a test that would have caught the bug has been added` but it is not clear to me which bug it resolves, also there is no issue for this attached.

2023-08-03 15:06 UTC, 0xmad commented
@0xisk thanks, remove logout after unsuccessful upload.
Regarding the bug: it fixes bugs related to unsuccessful uploads. Tests are added to e2e folder.

2023-08-04 09:18 UTC, 0xisk commented
> @0xisk thanks, remove logout after unsuccessful upload. Regarding the bug: it fixes bugs related to unsuccessful uploads. Tests are added to e2e folder.

For all the invalid backup files it shows `This ciphertext is not authentic`, I think that is a vague response to the user, I'd say rather we could print in this case `This backup file is not authentic`

2023-08-04 09:19 UTC, 0xisk requested changes

2023-08-04 09:19 UTC, 0xisk commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] e2e tests are passed locally
```suggestion
- [ ] E2E tests are passed locally
```

2023-08-04 14:16 UTC, 0xmad commented
> > @0xisk thanks, remove logout after unsuccessful upload. Regarding the bug: it fixes bugs related to unsuccessful uploads. Tests are added to e2e folder.
> 
> For all the invalid backup files it shows `This ciphertext is not authentic`, I think that is a vague response to the user, I'd say rather we could print in this case `This backup file is not authentic`

It's not possible to distinguish these errors and this is not a common case for user.

2023-08-04 15:15 UTC, 0xisk commented
> > > @0xisk thanks, remove logout after unsuccessful upload. Regarding the bug: it fixes bugs related to unsuccessful uploads. Tests are added to e2e folder.
> > 
> > 
> > For all the invalid backup files it shows `This ciphertext is not authentic`, I think that is a vague response to the user, I'd say rather we could print in this case `This backup file is not authentic`
> 
> It's not possible to distinguish these errors and this is not a common case for user.

Actually `getAuthenticCiphertext()` which throw this error, only used through `uploadEncryptedStorage()` functions in all backup supported services. So I think we can just rename this function to be `getAuthenticBackup()` and the error would be `This Backup file is not authentic`

2023-08-07 08:27 UTC, 0xisk approved these changes
Approved, thanks @0xmad!

2023-08-07 13:05 UTC, merged