Docs/whole update
CryptKeeperZK/crypt-keeper-extension pull request #857
Opened 2023-09-11 19:04 UTC by 0xisk

## Explanation

Enhancing the existing docs. 

## Related Issues

N/A

## Screenshots

N/A

## Manual Testing Steps

N/A

## Pre-Merge Checklist

- [ ] PR template is filled out
- [ ] Pre-commit and pre-push hook checks are passed
- [ ] E2E tests are passed locally
- [ ] **IF** this PR fixes a bug, a test that _would have_ caught the bug has been added
- [ ] PR is linked to the appropriate GitHub issue
- [ ] PR has been added to the appropriate release Milestone

> PR template source from [github.com/MetaMask](https://github.com/MetaMask)

2023-09-11 19:20 UTC, 0xmad requested changes
@0xisk thanks, there are some comments

2023-09-11 19:20 UTC, 0xmad commented on docs/src/guides/integration/_intro.md
> +* `createDummyRequest`: Creates a dummy request and returns the result.
We don't have this method and we need to keep this method list relevant.

2023-09-11 19:20 UTC, 0xmad commented on docs/src/guides/integration/connect.md
> +```
Why do we need this internal code snippet?

2023-09-11 19:20 UTC, 0xmad commented on docs/src/guides/integration/create-identity.md
> +```
The same here. Why do we need this code? How will it help to use provider methods?

2023-09-11 19:20 UTC, 0xmad commented on docs/src/what-is-cryptkeeper/_intro.md
> +> [![Video](https://img.youtube.com/vi/F5ic66_eNAs/maxresdefault.jpg)](https://www.youtube.com/watch?v=F5ic66_eNAs)
I think these links are outdated

2023-09-12 11:58 UTC, 0xisk commented on docs/src/what-is-cryptkeeper/_intro.md
> +> [![Video](https://img.youtube.com/vi/F5ic66_eNAs/maxresdefault.jpg)](https://www.youtube.com/watch?v=F5ic66_eNAs)
I moved those to resources.

2023-09-12 12:04 UTC, 0xisk commented
@0xmad thanks for your review. I moved the videos to resources under "Old Video Resources" title. And for the other comments they would be fixed in another PR because its dependent on what I am working on now which is doing enhancements to the provider functions. So we can get this PR merged so I can test the `deployDocs` workflow.

2023-09-12 14:08 UTC, merged